Remove extra line in error output

diff --git a/.local/sbin/ip-address b/.local/sbin/ip-address
--- a/.local/sbin/ip-address
+++ b/.local/sbin/ip-address
@@ -4,7 +4,7 @@ PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
 
 PATH_IP=$(which ip)
 if [ $? -ne 0 ]; then
-  echo "Error: cannot find utility named 'ip' in PATH.\n" 1>&2
+  echo "Error: cannot find utility named 'ip' in PATH." 1>&2
   exit 1
 fi
 
